config/routes.rb
Rails.application.routes.draw do
  seems_rateable
  get '/', to: 'home#index'
  
  resources :faculties, only: [:index, :show]

end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	belongs_to :university
	belongs_to :study
	seems_rateable # :quality, :speed, :effectiveness
	scope :order_by_score, -> { order global_score: :desc}

	def self.search(text)
		params = text.split(" ")
		conditions = []
		params.each do |param|
			conditions << "studies.name like '%#{param}%' OR universities.city like '%#{param}%'"
		end
		joins(:study, :university).where(conditions.join(" OR "))
	end
end

app/models/study.rb
class Study < ActiveRecord::Base
	has_many :faculties
	has_many :universities, through: :faculties

	#def self.search(text)
		#where("name like ?", "%#{text}%")
	#end
end

app/models/university.rb
class University < ActiveRecord::Base
	has_many :studies, through: :faculties
	has_many :faculties
	seems_rateable # :quality, :speed, :effectiveness
end

app/models/user.rb
class User < ActiveRecord::Base
	  seems_rateable_rater
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find 5
  end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
	def index
		#@faculties = Faculty.all
		#@faculties_ord = Faculty.all.sort { |a, b| b.global_score.to_i <=> a.global_score.to_i }
		@faculties= Faculty.order_by_score
		if params[:text]
			@faculties = Faculty.order_by_score.search(params[:text])
		end
	end

	def show
		@faculty = Faculty.find(params[:id])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
			@universities= University.all
			#@studies = Study.all
	end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
	def create
		SeemsRateable::Rate.create(rate_params)
	end

	private

	def rate_params
		params.require(:rate).permit(:rateable_id, :rateable_type, :stars)
	end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
	def index
		
	end
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
	def index
		@universities= University.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/faculties/index.html.erb
<!-- aqui empieza busqueda-->

<%= form_tag(faculties_path, method: "get") do %>
  <%= text_field_tag :text, params[:text], class: "search" %>
  <%= submit_tag("Search", class: "button_search") %>
<% end %>

<!--%=select_tag "study_name", options_for_select(["Derecho", "Medicina", "Informática", "Filologia"]), class: 'select'% >

< %=select_tag "faculty_city_name", options_for_select(["Madrid", "Barcelona"])%-->

<!-- se acaba la busqueda-->

<ul class="all_faculty_list">
	<% @faculties.each do |faculty| %>
		<li class="faculties_list">
			 <%= link_to faculty_path(faculty.id), class:"path" do %>
				<div class="boton_enlace"></div>
				<%= image_tag(faculty.university.image, class: "uni_image") %>
				<h5 class="study_name_list">
					<p></p>
				<%= faculty.study.name %></h5>
				<p class="description"><%= faculty.study.description %></p>
			<% end %>

			<div class="pepevote">
			<%= rating_for faculty %>
			</div>

			<!--<div class="ok_like"></div>
			<p class="global_score">--><!--%= faculty.global_score %></p>
			<div class="dislike"></div>
			<div class="spaceleft"></div>-->
		</li>
	<% end %>
</ul>

app/views/faculties/show.html.erb
			<div class="showvote">
			<%= rating_for @faculty %>
			</div>
<article id="bodybox">
	<div class="box">
		<p><%= image_tag(@faculty.university.image, class: "uni_image") %></p>
		<p class="studyname"><%= @faculty.study.name%></p><br>


		<p class="city">Ciudad: <%= @faculty.university.city%></p><br>
		<p class="students_faculty">Nota de Acceso: "<%= @faculty.acess_notes%>"</p><br>

		<p class="students_faculty">Alumnos en la facultad: <%= @faculty.students_number%><br></p>

		<p class="description_faculty">Description:</p>

		<p class="description_study"> <%= @faculty.study.description%><br></p>

		<seciton class="description_general_faculty">

				<div class="stud_teacher_number"><%= @faculty.university.name%><br></div><br>

				<div class="description_university"><%= @faculty.university.description%></div><br>

				<div class="stud_teacher_number">Alumnos en la universidad: <%= @faculty.university.students_number%></div><br>

				<div class="stud_teacher_number">Pofesores en la universidad: <%= @faculty.teachers_number%></div><br>
		</section>
	</div>
	<div id="latitud"> <%= @faculty.latitud %> </div>
	<div id="longitud"> <%= @faculty.longitud %> </div>
	<div id="mapa"></div>
</article>

app/views/home/index.html.erb
<p>Helo!</p>
<ul>
<% @universities.each do |university| %>
	<p><%= image_tag(university.image) %></p>
	<% university.faculties.each do |faculty|%>
		<li>
			<p><%= faculty.study.name %></p>
			<p><%= faculty.study.description %></p>
		</li>
	<%end%>
<%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Univercity</title>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=true"></script>
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application', defer: :true %>
	  <%= csrf_meta_tags %>
</head>
<body onload="showlocation()">

<%= yield %>

</body>
</html>